/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul_laporan.view;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modul_db.KoneksiDatabase;
/**
 *
 * @author Asep Supriyanto
 */
public class viewInternalLaporan extends javax.swing.JInternalFrame {

    
    private DefaultTableModel model;

    /**
     * Creates new form viewInternalLaporan
     */
    public viewInternalLaporan() {
        initComponents();
        model = new DefaultTableModel();
        tabelLaporan.setModel(model);
        model.addColumn("ID Transaksi");
        model.addColumn("Tanggal Transaksi");
        model.addColumn("Jumlah Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Satuan Produk");
        model.addColumn("Jenis Produk");
        model.addColumn("Harga Produk");

        tampilDataLaporan();
    }

    public JButton getTombolEksport() {
        return tombolEksport;
    }

    public void setTombolEksport(JButton tombolEksport) {
        this.tombolEksport = tombolEksport;
    }
    
private void tampilDataLaporan(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * FROM laporan";
        
        try {        
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                //mengambil hasil query variabel sql
                Object[] hasil;
                hasil = new Object[6];//karena ada 7 filed ditabel pelanggan
                hasil[0] = res.getString("idTransaksi");
                hasil[1] = res.getString("tglTransaksi");
                hasil[2] = res.getString("jumlahProduk");
                hasil[3] = res.getString("namaProduk");
                hasil[4] = res.getString("satuanProduk");
                hasil[5] = res.getString("jenisProduk");
                hasil[5] = res.getString("hargaProduk");
                
               model.addRow(hasil);
               

                
            }
        } catch (SQLException ex) {
            Logger.getLogger(viewInternalLaporan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();
        tombolEksport = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 235, 213));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Laporan");

        tabelLaporan.setBackground(new java.awt.Color(228, 235, 213));
        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelLaporan);

        tombolEksport.setText("Eksport Excel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombolEksport)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolEksport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelLaporan;
    private javax.swing.JButton tombolEksport;
    // End of variables declaration//GEN-END:variables
}
