/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul_transaksi.view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import modul_transaksi.controller.ControllerTransaksi;

/**
 *
 * @author mufid
 */
public class ViewTransaksiLanjutan extends javax.swing.JFrame {

    private ControllerTransaksi cT;

    /**
     * Creates new form ViewTransaksiLanjutan
     */
    public ViewTransaksiLanjutan() {
        initComponents();
        this.setTitle("Pembayaran");
    }

    public ViewTransaksiLanjutan(JTextField bayarTF, JLabel totalBayarLbl) {
        this.bayarTF = bayarTF;
        this.totalBayarLbl = totalBayarLbl;
    }

    public ViewTransaksiLanjutan(String tagihan) {
        initComponents();
        totalBayarLbl.setText(tagihan);
        
    }
    
    

    public JButton getBayarButton1() {
        return bayarButton;
    }

    public JTextField getBayarTF() {
        return bayarTF;
    }

    public JButton getKembaliButton1() {
        return kembaliButton1;
    }

    public JTextField getKembaliTF() {
        return kembalianTF;
    }

    public JLabel getTotalBayarLbl() {
        return totalBayarLbl;
    }

    public void hitungTagihan() {
        int totalHarga = 0;
        int totalBayar = 0;

        totalHarga = Integer.parseInt(totalBayarLbl.getText().replace("Rp. ", ""));
        if (!bayarTF.getText().isEmpty()) {
            totalBayar = Integer.parseInt(bayarTF.getText());
        }

        int kembalian = totalBayar - totalHarga;

        if (kembalian < 1) {
            kembalianTF.setText("TIDAK BISA HUTANG! TOLONG BAYAR FULL");
        } else {
            kembalianTF.setText(kembalian + "");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bayarButton = new javax.swing.JButton();
        kembaliButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        kembalianTF = new javax.swing.JTextField();
        bayarTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalBayarLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(228, 235, 213));

        bayarButton.setText("BAYAR");
        bayarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bayarButtonMouseClicked(evt);
            }
        });

        kembaliButton1.setText("KEMBALI");
        kembaliButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliButton1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 157, 160));
        jLabel6.setText("KEMBALI");

        kembalianTF.setEditable(false);

        bayarTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bayarTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayarTFKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 157, 160));
        jLabel5.setText("BAYAR");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 157, 160));
        jLabel4.setText("TOTAL");

        totalBayarLbl.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 224, Short.MAX_VALUE)
                                .addComponent(kembaliButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bayarButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bayarTF)
                            .addComponent(kembalianTF)
                            .addComponent(totalBayarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalBayarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bayarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kembalianTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayarButton)
                    .addComponent(kembaliButton1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_kembaliButton1MouseClicked

    private void bayarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bayarButtonMouseClicked
        // TODO add your handling code here:
        int kembalian = Integer.parseInt(kembalianTF.getText());
        String bayar = bayarTF.getText();
        if (bayar == "" && kembalian == 0) {
            JOptionPane.showConfirmDialog(null,
                    "Selesaikan Pembayaran Terlebih Dahulu", "Pembayaran", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showConfirmDialog(null,
                    "Pembayaran Berhasil Dilakukan!", "Pembayaran", JOptionPane.DEFAULT_OPTION);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_bayarButtonMouseClicked

    private void bayarTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarTFKeyTyped
        // TODO add your handling code here:
        hitungTagihan();
    }//GEN-LAST:event_bayarTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransaksiLanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarButton;
    private javax.swing.JTextField bayarTF;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kembaliButton1;
    private javax.swing.JTextField kembalianTF;
    private javax.swing.JLabel totalBayarLbl;
    // End of variables declaration//GEN-END:variables
}
